name: T5-4.7 PLUS CI

on:
  workflow_dispatch:

jobs:
  build_t5-47-plus:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: sudo apt-get install git make python3 python3-pip cmake quilt
    - name: Build T5-4.7 Plus
      run: |
        cp config_T5-4.7-Plus config
        CFLAGS_EXTRA="-Wno-dangling-pointer" make
    - name: Deliver firmware
      uses: actions/upload-artifact@v4
      with:
        name: LILYGO_T5-4.7-PLUS_firmware
        path: ./bin/esp32s3/LILYGO_T5-4.7-PLUS/